name = "OMEinsum"
uuid = "ebe7aa44-baf0-506c-a96f-8464559b3922"
authors = ["Andreas Peter <andreas.peter.ch@gmail.com>"]
version = "0.1.0"

[deps]
BatchedRoutines = "a9ab73d0-e05c-5df1-8fde-d6a4645b8d8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[targets]
test = ["Test", "Einsum"]
